version: "3.8"
services:
  web:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./orders.db
    volumes:
      - .:/app
